ead:
  serviceRegistry:
    username: serviceregistry
    password: '123456sr'
  auth:
    jwtSecret: vyZJRRBBiKoc3ddQNOToWomazdwgrydKLCingvB6EWuypsyDga5yRfGrC1Rk7pGahvLu7z62macUcHeXGHYBcW
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost